### ISSUE TITLE
Dependency broken

### ISSUE THREAD

**Issue by cbobed** [dwslab/jRDF2Vec#19]
Hi all, 

I've cloned the repo, done the mvn clean install step, and it seems that jsonld-java is breaking the compiling (it seems that it's not published at jitpack.io as a bundle). I think it's not a direct dependency, but one of the dependencies used builds on it. Just to raise awareness :) 

Best,

**Comment by janothan** [comment]
Thank you very much for letting us know, @cbobed 👍🏻 I fixed this issue. It would be great if you would quickly test the latest commit and close this issue if it works. 

Generally: You can also just download the latest _working_ JAR [here](https://github.com/dwslab/jRDF2Vec/tree/jars).

**Comment by cbobed** [comment]
Hi @janothan , 

sorry for my late reply, I've been a little busy the last days. I'm afraid it still doesn't work: 

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jrdf2vec: Could not resolve dependencies for project de.uni-mannheim.informatik.dws:jrdf2vec:jar:1.0-SNAPSHOT: Could not find artifact com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.12.5 in central (https://repo1.maven.org/maven2) -> [Help 1] 

I think I changed the dependency to version 0.13.0 and it worked, but it was just a test.

**Comment by janothan** [comment]
Could you try to delete the directory in your local m2 repository (typically `/Users/<user>/.m2/repository/com/github/jsonld-java`) and retry it? You can use the latest commit, we fixed some more bugs (particularly related to windows os).

**Comment by cbobed** [comment]
I can confirm that it works. The tests were not passing but it might be caused on my side (a lot of them raising exceptions, probably due to missing python ... I'd have to delve a little bit into it - so far, I've built it using -DskipTests and -Dmaven.javadoc.skip=true
 as well). As the main problem was the dependency, I close the issue.
